### PR TITLE
added support for json post exchange

### PR DESCRIPTION
**Pull request by chris-kruining**
`getForExchange` did not offer support for `JSON` based `POST` requests for data exchange

### CODE REVIEW

**Comment by chris-kruining** [comment]
I might add that I have not received any "meta-data" in the exchange for ages. data like customer details and back information is missing

**Comment by andypieters** [comment]
> I might add that I have not received any "meta-data" in the exchange for ages. data like customer details and back information is missing

The exchange call should not contain customer data,
The fields in the exchange can be found here.
The sdk uses only the order_id to fetch the transactie, which should contain the customer data.

As for this pull request, i will test this today.
If it works it will be merged, thanks for contributing!

**Comment by chris-kruining** [comment]
@andypieters I ment `stornoDetails` and `enduser`. these used to provide data in the past, that is where I used to store the BIC of the bank in question for later displaying to the retailer (in the past might have been 1.5 to 2 years ago)

**Comment by andypieters** [comment]
@chris-kruining Maybe we did sent that data in the past, iam not sure.
But i can also imagine that sending customer data to some url might have privacy considerations.
You can still get that data by fetching the transaction using the sdk, but it's not included in the exchange call.

**Pull request merged**
