### PR TITLE
Add MIT license

### PR DESCRIPTION
**Pull request by curry684**
Please add an open and unburdened license to the project as we and many of our clients need it for compliance reasons.

### CODE REVIEW

**Comment by curry684** [comment]
I see that individual files are marked GPLv2, this is *highly undesirable* without a [linking exception](https://en.wikipedia.org/wiki/GPL_linking_exception). In its current state the library does not comply to common inclusion standards.

**Comment by andypieters** [comment]
The license should be MIT the least restricting license.

**Comment by curry684** [comment]
Any chance of a formal release with this? Compliance....   😉

**Comment by andypieters** [comment]
iam so sorry, i completely missed your message.
I'll create a formal remase now

**Pull request merged**
